language: java
jdk:
   - openjdk11

addons:
    sonarcloud:
        organization: leleuni
        token: 124b00d56855595c8f00831ea48f9a147894fee3

script:
    - ant build
    - sonar-scanner
